services:
  - type: web
    name: death-announcements-api
    rootDir: server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false

  - type: static
    name: death-announcements-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist/client